/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica_5;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Specm
 */
public class ListarAluno extends javax.swing.JInternalFrame {

    /**
     * Creates new form ListarAluno
     */
    public ListarAluno() {
        initComponents();
        
        try {
      
        String url = "jdbc:mysql://localhost:3306/bd";
        String userName = "root"; 
        String password = "";    
    
        Connection minhaConexao; 
        PreparedStatement minhaDeclaracao;
        ResultSet rs;
        String sql,nomeAluno;
        int faltas;
        double nota1,nota2;
    
        minhaConexao = DriverManager.getConnection(url, userName, password);
      
        sql = "select * from alunos";
        minhaDeclaracao = minhaConexao.prepareStatement(sql);
        rs = minhaDeclaracao.executeQuery();
      
        while(rs.next()) 
        { 
            nomeAluno = rs.getString("nomeAluno");
            faltas = rs.getInt("faltas");
            nota1 = rs.getDouble("nota1");
            nota2 = rs.getDouble("nota2");
            resultado.append("id{" + rs.getInt("idalunos") + "}__________________________________\n");
            Aluno aluno = new Aluno(nomeAluno, faltas, nota1, nota2);
            resultado.append(aluno.toString() + "\n");
        }
      
        minhaConexao.close();
      } 
      catch (SQLException e) {
        Logger.getLogger(ListarAluno.class.getName()).log(Level.SEVERE, null, e);
      }
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        bFechar = new javax.swing.JButton();

        setTitle("[Alunos] Listar");

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        bFechar.setText("Fechar");
        bFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 374, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(bFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFecharActionPerformed

        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_bFecharActionPerformed

    public void setPosicao() {
      Dimension d = this.getDesktopPane().getSize();
      this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2); 
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bFechar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    // End of variables declaration//GEN-END:variables
}
