/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inetface_grafica_4;

/**
 *
 * @author Specm
 */
public class IMC extends javax.swing.JInternalFrame {

    /**
     * Creates new form IMC
     */
    public IMC() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        botaoCalcIMC = new javax.swing.JButton();
        varPeso = new javax.swing.JTextField();
        varAltura = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        janelaResultado = new javax.swing.JTextArea();
        botaoFechar = new javax.swing.JButton();

        jLabel1.setText("Peso Corporal (Em arrobas): ");

        jLabel2.setText("Altura (Em MT): ");

        botaoCalcIMC.setText("Calcular Decepcao");
        botaoCalcIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCalcIMCActionPerformed(evt);
            }
        });

        janelaResultado.setColumns(20);
        janelaResultado.setRows(5);
        jScrollPane1.setViewportView(janelaResultado);

        botaoFechar.setText("Tchau");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(varAltura, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addComponent(varPeso)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botaoCalcIMC, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)))
                    .addComponent(botaoFechar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(varPeso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(varAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoCalcIMC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  public static double divisao(double n, double d) {
    if (d != 0)
        return(n / d);
    else return(0);
  }
  
  public static double percentual(double todo, double parte) {
    return(divisao(parte, todo) * 100);  
  }
    
    public static double calcIMC(double pc, double alt) {
    return(divisao(pc, Math.pow(alt, 2)));  
    }
    
    public static String interpretarIMC(double pc, double alt) {
    double vlrIMC = calcIMC(pc, alt);
    
    if (vlrIMC < 18.5)
        return("baixo peso");
    else if (vlrIMC < 25.0)
            return("peso adequado");
         else if (vlrIMC < 30.0)
                 return("sobrepeso");
              else return("obesidade");
  }
    
    private void botaoCalcIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCalcIMCActionPerformed
        
        janelaResultado.setText("");

        try 
        {
        double peso = Double.parseDouble(varPeso.getText());
        double altura = Double.parseDouble(varAltura.getText());           
        
        String doubleparaString = String.format ("%.2f", calcIMC(peso, altura));
        janelaResultado.append("IMC: " + doubleparaString);
        janelaResultado.append("\n\n <<< " + interpretarIMC(peso, altura) + " >>>");
        }
        catch (NumberFormatException e)
        {
        janelaResultado.append(e.toString());    
        }
        
    }//GEN-LAST:event_botaoCalcIMCActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
                this.dispose();  
    }//GEN-LAST:event_botaoFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCalcIMC;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea janelaResultado;
    private javax.swing.JTextField varAltura;
    private javax.swing.JTextField varPeso;
    // End of variables declaration//GEN-END:variables
}
