/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica_3;

import java.awt.Dimension;

/**
 *
 * @author Specm
 */
public class Divisores_N extends javax.swing.JInternalFrame {

    /**
     * Creates new form Divisores_N
     */
    public Divisores_N() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        varN = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        botaoDivN = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultadoDivisores = new javax.swing.JTextArea();
        botaoFechar = new javax.swing.JButton();

        setTitle("Divisores de N");

        varN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNActionPerformed(evt);
            }
        });

        jLabel1.setText("N:");

        botaoDivN.setText("Divisores de N");
        botaoDivN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDivNActionPerformed(evt);
            }
        });

        resultadoDivisores.setColumns(20);
        resultadoDivisores.setRows(5);
        jScrollPane1.setViewportView(resultadoDivisores);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(varN, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(botaoDivN, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(botaoFechar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(varN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(botaoDivN))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botaoFechar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNActionPerformed

    private void botaoDivNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDivNActionPerformed
    
        try
        {
            int div = 0;
            resultadoDivisores.setText("");
            resultadoDivisores.append("Divisores:");
            int n = Integer.parseInt(varN.getText());
            for(int i = 1; i <= n; i++)
                if ((n % i) == 0)
                {
                    div++;
                    resultadoDivisores.append(String.format("%n%dº divisor = %d",div,i));
                }
            if (div == 2)
                resultadoDivisores.append(String.format("%n%nNúmero Primo"));
        }
        catch (NumberFormatException e)
        {
            resultadoDivisores.append("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_botaoDivNActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();  
    }//GEN-LAST:event_botaoFecharActionPerformed

    
    public void setPosicao() 
    {
        Dimension d = this.getDesktopPane().getSize();
        this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoDivN;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultadoDivisores;
    private javax.swing.JTextField varN;
    // End of variables declaration//GEN-END:variables
}
