/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica_3;

import java.awt.Dimension;

/**
 *
 * @author Specm
 */
public class FiguraChata extends javax.swing.JInternalFrame {

    /**
     * Creates new form FiguraChata
     */
    public FiguraChata() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        varN = new javax.swing.JTextField();
        botaoFazFigura = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        resultado = new javax.swing.JTextArea();
        botaoFechar = new javax.swing.JButton();

        setTitle("Figura Bacana");

        jLabel1.setText("N:");

        varN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varNActionPerformed(evt);
            }
        });

        botaoFazFigura.setText("faz figura");
        botaoFazFigura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFazFiguraActionPerformed(evt);
            }
        });

        resultado.setColumns(20);
        resultado.setRows(5);
        jScrollPane1.setViewportView(resultado);

        botaoFechar.setText("Fechar");
        botaoFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varN, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botaoFazFigura, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoFechar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(varN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoFazFigura))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoFechar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void varNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_varNActionPerformed

    private void botaoFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFecharActionPerformed
        this.dispose();  
    }//GEN-LAST:event_botaoFecharActionPerformed

    private void botaoFazFiguraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoFazFiguraActionPerformed
        
            try
            {
                resultado.setText("");
                int n = Integer.parseInt(varN.getText());
                int i , d;
                for(i = 1; i <= n; i++){
                    if (i == 1)
                    {
                        resultado.append(String.format("+"));
                        
                        for(d = 0; d < n; d++)
                            resultado.append(String.format("--"));
                            resultado.append(String.format("-+\n"));
                    }
                    resultado.append("! ");
                    for(d=0;d<n;d++)
                       resultado.append(String.format("%d ", i));
                       resultado.append("!\n");
            }
            resultado.append(String.format("+"));
            
            for(d = 0; d < n; d++)
                resultado.append(String.format("--"));
                resultado.append(String.format("-+"));
        }
        catch (NumberFormatException e)
        {
            resultado.append("Erro: " + e.getMessage());
        }
    }//GEN-LAST:event_botaoFazFiguraActionPerformed
    
public void setPosicao() 
{
    Dimension d = this.getDesktopPane().getSize();
    this.setLocation((d.width - this.getSize().width) / 2, (d.height - this.getSize().height) / 2);
}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoFazFigura;
    private javax.swing.JButton botaoFechar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea resultado;
    private javax.swing.JTextField varN;
    // End of variables declaration//GEN-END:variables
}
