/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interface_grafica_3;

/**
 *
 * @author Specm
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        janelaInterna = new javax.swing.JDesktopPane();
        menuBar = new javax.swing.JMenuBar();
        opcoes = new javax.swing.JMenu();
        divN = new javax.swing.JMenuItem();
        fBcana = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        sair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Principal");

        javax.swing.GroupLayout janelaInternaLayout = new javax.swing.GroupLayout(janelaInterna);
        janelaInterna.setLayout(janelaInternaLayout);
        janelaInternaLayout.setHorizontalGroup(
            janelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        janelaInternaLayout.setVerticalGroup(
            janelaInternaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        opcoes.setText("Opções");

        divN.setText("Divisores de \"n\"");
        divN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divNActionPerformed(evt);
            }
        });
        opcoes.add(divN);

        fBcana.setText("Figura Bacana");
        fBcana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBcanaActionPerformed(evt);
            }
        });
        opcoes.add(fBcana);
        opcoes.add(jSeparator1);

        sair.setText("Sair");
        sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairActionPerformed(evt);
            }
        });
        opcoes.add(sair);

        menuBar.add(opcoes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaInterna)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(janelaInterna)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void divNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divNActionPerformed
    
        Divisores_N divisores = new Divisores_N();
        
        janelaInterna.add(divisores);
        divisores.setVisible(true);
        divisores.setPosicao();

    }//GEN-LAST:event_divNActionPerformed

    private void sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairActionPerformed
            System.exit(0);
    }//GEN-LAST:event_sairActionPerformed

    private void fBcanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBcanaActionPerformed
        FiguraChata figuraBac = new FiguraChata();
        
        janelaInterna.add(figuraBac);
        figuraBac.setVisible(true);
        figuraBac.setPosicao();
    }//GEN-LAST:event_fBcanaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem divN;
    private javax.swing.JMenuItem fBcana;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JDesktopPane janelaInterna;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu opcoes;
    private javax.swing.JMenuItem sair;
    // End of variables declaration//GEN-END:variables
}
